### ISSUE TITLE
create conda feedstock

### ISSUE THREAD

**Issue by mattip** [scipy/oldest-supported-numpy#17]
When trying to update [this random feedstock](https://github.com/conda-forge/astroscrappy-feedstock) for python3.9, I noticed that this package, which would make it trivial to forward-support new python versions, does not seem to be available on conda. Would it make sense to add a feedstock there?

**Comment by rgommers** [comment]
Probably not. Conda has a completely different mechanism of controlling numpy versions (see `{{ pin_compatible('numpy') }}` [here](https://github.com/conda-forge/scipy-feedstock/blob/master/recipe/meta.yaml#L42)), so I'm not sure `oldest-supported-numpy` would be useful at all. Or am I missing something?

**Comment by mattip** [comment]
Ahh, right. The [documentation is helpful](https://conda-forge.org/docs/maintainer/knowledge_base.html#linking-numpy). Closing, thanks.
