### ISSUE TITLE
oldest-supported-numpy build fails on Apple Silicon

### ISSUE THREAD

**Issue by kbourgoin** [scipy/oldest-supported-numpy#19]
I'm trying to install a project which relies on `oldest-supported-numpy` and it won't build because it's trying to install `numpy==1.19.3` and it looks to me like numpy doesn't build on `arm64` until `1.20.0` using python 3.9.5.

I'm not super familiar with the numpy build system, so I may be wrong about needing `>=1.20.0`. It's how it works on my system right now and the failures are a bunch of clang errors I can't debug.

**Comment by rgommers** [comment]
Thanks for the report @kbourgoin 

> I'm not super familiar with the numpy build system, so I may be wrong about needing `>=1.20.0`. It's how it works on my system right now and the failures are a bunch of clang errors I can't debug.

Yes indeed, at least `1.20.0`. It's possible that there are fixes in `1.20.1-1.20.3` that are needed as well. Right now there are no numpy wheels for macOS M1 yet (either `arm64` or `universal2`), so it's not easy to figure out what the correct lower limit is. Once those wheels show up (I think we'll have them for `1.21.0`) then that should be the lower limit.

**Comment by charris** [comment]
There is a universal2 wheel for NumPy 1.21.0rc1.

**Comment by kbourgoin** [comment]
I'm not very familiar with numpy builds, but `1.20.0` builds without issue for me. Do we need to wait for those wheels to be published before the proposed fix can be merged? I only pip install `oldest-supported-numpy` as part of a dependency, so I'm a bit out of my depth here.

**Comment by rgommers** [comment]
> I'm not very familiar with numpy builds, but 1.20.0 builds without issue for me. Do we need to wait for those wheels to be published before the proposed fix can be merged? 

No we don't, we can merge it now. But once 1.21.0 arrives in a few weeks, I'd like to bump the version number. So if you depend on the reproducibility of 1.20.0, you should probably use `oldest-supported-numpy==0.9`.

**Comment by kbourgoin** [comment]
@rgommers any chance of this getting merged soon?

**Comment by rgommers** [comment]
Yes, let's get that fix in. The next step is releasing it - let's do that straight away too, otherwise it's still not useful.

**Comment by rgommers** [comment]
Okay, `v0.9` is on PyPI now.

**Comment by kbourgoin** [comment]
Thank you!
