### ISSUE TITLE
ERROR: ResolutionImpossible with pip install

### ISSUE THREAD

**Issue by shz9** [scipy/oldest-supported-numpy#21]
I'm trying to install a package that lists `oldest-supported-numpy`  in its `.toml` file and I'm seeing that there are conflicts in the package specifications. To get to the bottom of it, I tried installing the package separately:

```
pip install oldest-supported-numpy
```

And got the following error message:

```
Collecting oldest-supported-numpy
  Using cached oldest_supported_numpy-0.8-py3-none-any.whl (3.7 kB)
  Using cached oldest_supported_numpy-0.7-py3-none-any.whl (3.6 kB)
  Using cached oldest_supported_numpy-0.6-py3-none-any.whl (3.5 kB)
  Using cached oldest_supported_numpy-0.5-py3-none-any.whl (3.5 kB)
  Using cached oldest_supported_numpy-0.4-py3-none-any.whl (3.5 kB)
  Using cached oldest_supported_numpy-0.3-py3-none-any.whl (3.5 kB)
  Using cached oldest_supported_numpy-0.2-py2.py3-none-any.whl (2.5 kB)
  Using cached oldest_supported_numpy-0.1-py2.py3-none-any.whl (2.2 kB)
ERROR: Cannot install oldest-supported-numpy==0.1, oldest-supported-numpy==0.2, oldest-supported-numpy==0.3, oldest-supported-numpy==0.4, oldest-supported-numpy==0.5, oldest-supported-numpy==0.6, oldest-supported-numpy==0.7 and oldest-supported-numpy==0.8 because these package versions have conflicting dependencies.

The conflict is caused by:
    oldest-supported-numpy 0.8 depends on numpy==1.14.5; python_version == "3.7" and platform_machine != "aarch64" and platform_system != "AIX" and platform_python_implementation != "PyPy"
    oldest-supported-numpy 0.7 depends on numpy==1.14.5; python_version == "3.7" and platform_machine != "aarch64" and platform_system != "AIX"
    oldest-supported-numpy 0.6 depends on numpy==1.14.5; python_version == "3.7" and platform_system != "AIX"
    oldest-supported-numpy 0.5 depends on numpy==1.14.5; python_version == "3.7" and platform_system != "AIX"
    oldest-supported-numpy 0.4 depends on numpy==1.14.5; python_version == "3.7" and platform_system != "AIX"
    oldest-supported-numpy 0.3 depends on numpy==1.14.5; python_version == "3.7" and platform_system != "AIX"
    oldest-supported-numpy 0.2 depends on numpy==1.14.5; python_version == "3.7" and platform_system != "AIX"
    oldest-supported-numpy 0.1 depends on numpy==1.14.5; python_version == "3.7" and platform_system != "AIX"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```

More details: 
- OS: `CentOS Linux 7`
- Python version: `3.7.7`
- numpy version: `1.20.2`

Any ideas on how to resolve this?

**Comment by astrofrog** [comment]
@shz9 - just to check, when using this in a .toml file, what other packages are listed there?

**Comment by shz9** [comment]
This is the `.toml` file in question:
[https://github.com/tskit-dev/msprime/blob/main/pyproject.toml](https://github.com/tskit-dev/msprime/blob/main/pyproject.toml)

But just to re-iterate, I'm getting the error above even when I run `pip install oldest-supported-numpy` separately.

**Comment by astrofrog** [comment]
@shz9 - thanks!

Could you try and see if you get the error if you start off in an environment that does not have numpy already installed? (since it looks like you have numpy 1.20.2 installed already)

**Comment by shz9** [comment]
Strangely enough, I just tried the steps above with python `3.6.10` and the installation worked fine. 
Is there some sort of incompatibility with `3.7.7` that results in the error above?

**Comment by astrofrog** [comment]
Just to add another data point, Python 3.7.4 on MacOS X works fine:

```
% python3.7 -m venv test-old-numpy
% source test-old-numpy/bin/activate
% pip install --upgrade pip
Collecting pip
  Downloading https://files.pythonhosted.org/packages/cd/82/04e9aaf603fdbaecb4323b9e723f13c92c245f6ab2902195c53987848c78/pip-21.1.2-py3-none-any.whl (1.5MB)
    100% |████████████████████████████████| 1.6MB 5.1MB/s 
Installing collected packages: pip
  Found existing installation: pip 19.0.3
    Uninstalling pip-19.0.3:
      Successfully uninstalled pip-19.0.3
Successfully installed pip-21.1.2
% pip install oldest-supported-numpy
Collecting oldest-supported-numpy
  Downloading oldest_supported_numpy-0.8-py3-none-any.whl (3.7 kB)
Collecting numpy==1.14.5
  Using cached numpy-1.14.5-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (4.7 MB)
Installing collected packages: numpy, oldest-supported-numpy
Successfully installed numpy-1.14.5 oldest-supported-numpy-0.8
% python --version
Python 3.7.4
```

I'll try Python 3.7.7 on Linux later on.

**Comment by astrofrog** [comment]
@shz9 - what if you try and install ``pip install numpy==1.14.5`` into the virtual environment directly, does that work?

**Comment by shz9** [comment]
I think you may have identified the problem.
I'm working in a computing cluster environment and sometimes I get this error message for some versions of packages that I'm trying to install.

```{bash}
pip install numpy==1.14.5
Defaulting to user installation because normal site-packages is not writeable
Ignoring pip: markers 'python_version < "3"' don't match your environment
Looking in links: /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/gentoo/avx512, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/gentoo/avx2, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/gentoo/generic, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic
ERROR: Could not find a version that satisfies the requirement numpy==1.14.5 (from versions: 1.16.4, 1.16.6, 1.17.3, 1.17.5, 1.18.4, 1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.19.5, 1.20.0, 1.20.1, 1.20.2)
ERROR: No matching distribution found for numpy==1.14.5
```

Is it correct to say that for `oldest-supported-numpy` to work with python `3.7` it needs `numpy==1.14.5`?

**Comment by rgommers** [comment]
> Is it correct to say that for `oldest-supported-numpy` to work with python `3.7` it needs `numpy==1.14.5`?

Yes, that's correct.

**Comment by rgommers** [comment]
> I'm working in a computing cluster environment and sometimes I get this error message for some versions of packages that I'm trying to install.

If you're not able to use PyPI but must use a local index server on your cluster, I don't think `oldest-supported-numpy` is the best solution. Instead, you'll want to copy just the requirement you need into your `pyproject.toml`, and build against a version that's actually available.

**Comment by shz9** [comment]
I see. The thing is, I was trying to install an external software that used `oldest-supported-numpy` in its `.toml`, so I didn't have a choice in this case.

Thanks all for your help. To summarize the issue for others who may encounter it:

If you're installing `oldest-supported-numpy` with python `3.7`, make sure that your system supports installing `numpy==1.14.5`. Otherwise, you'll see the error the I reported above. The solution for me was to switch to python `3.8` on the computing cluster.
