### ISSUE TITLE
There is no pre-build package for numpy 1.20.0 for darwin/arm64/cp39 at PyPI

### ISSUE THREAD

**Issue by mmac-m3a** [scipy/oldest-supported-numpy#23]
Please, point to version 1.21.2 for this ABI/platform combo. `numpy` 1.20.0 also fails to build from source code for this combo. This currently breaks (at least) `fastparquet` 0.7.1 for M1 Mac users.

**Comment by rgommers** [comment]
Looks like we need to release the fix for this asap to fix that `fastparquet`/`pandas` issue. I'll try to do so later today. I will leave this issue open until it is done.

**Comment by rgommers** [comment]
https://pypi.org/project/oldest-supported-numpy/0.10/ is up, this should fix things. thanks again @mmac-m3a

**Comment by mmac-m3a** [comment]
Yup, all seems to be fine again for darwin/arm64 with Python 3.9. Thanks!
