### ISSUE TITLE
Require 1.17.5 for big-endian platforms

### ISSUE THREAD

**Issue by pitrou** [scipy/oldest-supported-numpy#29]
Before 1.17.5 there was a bug in Numpy that made it unusable on big-endian platforms such as `s390x`.
See https://github.com/numpy/numpy/pull/14937 and https://github.com/numpy/numpy/milestone/78?closed=1

Example symptoms (traceback in pytest format, sorry):
```python
a = array([0, 2], dtype=int32), dtype = <class 'numpy.int32'>

    @set_module('numpy')
    def ascontiguousarray(a, dtype=None):
        """
        Return a contiguous array (ndim >= 1) in memory (C order).
    
        Parameters
        ----------
        a : array_like
            Input array.
        dtype : str or dtype object, optional
            Data-type of returned array.
    
        Returns
        -------
        out : ndarray
            Contiguous array of same shape and content as `a`, with type `dtype`
            if specified.
    
        See Also
        --------
        asfortranarray : Convert input to an ndarray with column-major
                         memory order.
        require : Return an ndarray that satisfies requirements.
        ndarray.flags : Information about the memory layout of the array.
    
        Examples
        --------
        >>> x = np.arange(6).reshape(2,3)
        >>> np.ascontiguousarray(x, dtype=np.float32)
        array([[0., 1., 2.],
               [3., 4., 5.]], dtype=float32)
        >>> x.flags['C_CONTIGUOUS']
        True
    
        Note: This function returns an array with at least one-dimension (1-d)
        so it will not preserve 0-d arrays.
    
        """
>       return array(a, dtype, copy=False, order='C', ndmin=1)
E       ValueError: ndmin bigger than allowable number of dimensions NPY_MAXDIMS (=32)
```

**Comment by pitrou** [comment]
FYI @kszucs

**Comment by rgommers** [comment]
Thanks for the report @pitrou. On what Python versions do you need support? For Python 3.8 this requirement can be bumped to `1.17.5`:
```
numpy==1.17.3; python_version=='3.8' and (platform_machine!='arm64' or platform_system!='Darwin') and platform_machine!='aarch64' and platform_python_implementation != 'PyPy'
```
On older Python versions it'd be a very large bump (default is now `1.14.5` for py37), and it isn't 100% clear to me how often this problem would show up.

There is no single way to say "all big-endian platforms" in `setup.cfg` metadata I believe. The relevant tags are probably `s390x`, `AIX` and `ppc64le` - am I missing anything there?

**Comment by pitrou** [comment]
Well, our s390x CI uses 3.8 by chance :-) I would be ok with not fixing for previous versions.

"ppc64le" is little-endian (note the "le" suffix :-)). AIX is orthogonal as it's an OS, not a machine architecture. I think we can start with "s390x" and see if anything else pops up.

**Comment by rgommers** [comment]
Special-casing s390x sounds good to me. Were you planning to open a PR, or should I?

> "ppc64le" is little-endian (note the "le" suffix :-)).

🤦🏼 looks like I need more coffee

**Comment by pitrou** [comment]
If you don't mind I'll let you open a PR :-)

**Comment by rgommers** [comment]
It's always a pain to figure out what the correct metadata is to identify a platform. I believe it's `platform_system=='s390x'`, but I can't test it. Opened gh-30 with that change. Could you have a look @pitrou?

It should correspond to the output of `import platform; print(platform.system())` I think.

**Comment by kszucs** [comment]
It could be tested on travis, at least arrow [runs the s390x build](https://github.com/apache/arrow/blob/master/.travis.yml#L86) there.
