### ISSUE TITLE
Update versioning & deployment to have a new release automatically for each commit

### ISSUE THREAD

**Issue by rgommers** [scipy/oldest-supported-numpy#31]
The churn in this repo is low enough that it's not really annoying yet, but it would be a nice change to have each commit automatically be uploaded to PyPI with the correct version bump.

Right now to make any commit effective for users, we need:
1. A commit with a version bump in `setup.cfg`, and adding the corresponding release tag (e.g. `v0.13`)
2. Run `python setup.py sdist`, `python setup.py bdist_wheel` and `twine upload dist/*`.

**Comment by tupui** [comment]
That would be nice to continuously deploy main 👍
