### ISSUE TITLE
Change version number to 1.0?

### ISSUE THREAD

**Issue by rgommers** [scipy/oldest-supported-numpy#32]
This package is now quite widely depended on, including by mature projects like Pandas, Arrow, and AstroPy. And it's quite stable.

**Comment by astrofrog** [comment]
Just to check, do we think semantic versioning makes sense here, or would it be better to use e.g calendar based versioning?

**Comment by rgommers** [comment]
I don't have a real preference. Calendar-based may be extra data that's useful. I have no experience with it though. Certainly there's no semantic meaning for major version number bumps, and we're not using bug-fix versions either.

**Comment by rgommers** [comment]
On second thought, I like CalVer. Let's go for `yyyy.mm.dd`?

**Comment by astrofrog** [comment]
Sounds good!

**Comment by rgommers** [comment]
Done: https://pypi.org/project/oldest-supported-numpy/2022.1.30/

> Let's go for `yyyy.mm.dd`?

It turns out that the sdist and wheel names turn `01` into `1` for the month, so leave out the zero.
