### ISSUE TITLE
add a linux / x86 tags to the environmental markets for pypy

### ISSUE THREAD

**Issue by fgregg** [scipy/oldest-supported-numpy#36]
right now, the environmental marker for pypy don't indicate any other environmental markers

```
    numpy==1.19.0; python_version=='3.6' and platform_python_implementation=='PyPy'
    numpy==1.20.0; python_version=='3.7' and platform_python_implementation=='PyPy'
```

but the only wheels available on pypi are manylinux2010, x86 wheels. 

perhaps add these tags to the environmental markers?

**Comment by fgregg** [comment]
also, let me say i really appreciate this library!!

**Comment by rgommers** [comment]
I would say this still applies to other platforms, those will require building NumPy for PyPy from source. If we add `x86_64` markers then we may cause problems for users on other platforms.
