### ISSUE TITLE
Add correct requirement for py37 and arm64 M1 processors

### ISSUE THREAD

**Issue by lxbader** [scipy/oldest-supported-numpy#48]
Would it be possible to add a requirement like
`numpy==1.21.0; python_version=='3.7' and platform_machine=='arm64' and platform_system=='Darwin'`
for users with new ARM64 processors who still need to run pandas and other packages on python 3.7?

I would open a PR but don't seem to have the permissions.

**Comment by rgommers** [comment]
IIRC neither PyPI nor conda has 3.7 binaries for macOS arm64, so it's not clear to me that that is a valid combination at all. And 1.22.0 requires Python >=3.8, so not have a pin should already give you a 1.21.x sdist. So this doesn't look useful to me. If I'm missing something, can you please explain in more detail @lxbader?

> I would open a PR but don't seem to have the permissions.

This is a regular public repo, so you do have permissions.

**Comment by rgommers** [comment]
Ah okay, that makes sense. Can you please try to open a PR? The standard "fork-clone-sendPR" workflow for GitHub definitely works. If you really have an issue with that, please post the diff that works for you.

**Comment by henryiii** [comment]
How did you get Python 3.7 running on macOS ARM? The patches have never been backported past 3.8 AFAICK.

**Comment by lxbader** [comment]
@rgommers Not sure what's going wrong with me trying to push - new machine so some setup may be sketchy, but it does look like I have SSH access and everything should work, but it doesn't. It's probably easiest to just write the diff here:

`numpy==1.21.0; python_version=='3.7' and platform_machine=='arm64' and platform_system=='Darwin'` needs to be added to the ARM64 requirements, and the default numpy requirements for 3.7 need to be amended to exclude this combination:

`numpy==1.14.5; python_version=='3.7' and (platform_machine!='arm64' or platform_system!='Darwin') and platform_machine!='aarch64' and platform_machine!='loongarch64' and platform_system!='AIX' and platform_python_implementation != 'PyPy'`

@henryiii cloning the current pyenv and installing it let us install python 3.7.13 without problems happily!

**Comment by henryiii** [comment]
You can just edit the file directly in GitHub, that will automatically make a fork and start the PR process. It's the little pencil icon at the top when viewing the file. I'd do it but I can't test it, so it seems safer to let you do it if you can (via that edit button).

That's a build-from-source, plus a few patch releases past the final binary release, so maybe they were accepting fixes for ARM? I'd be a little nervous and would double test everything to make sure it works, but interesting if it does!
