### ISSUE TITLE
Add new entry for PyPy 3.8?

### ISSUE THREAD

**Issue by astrofrog** [scipy/oldest-supported-numpy#55]
It looks like Numpy 1.22 might now have wheels for PyPy 3.8? If so, we should update the following entry:

```
numpy; python_version>='3.8' and platform_python_implementation=='PyPy'
```

and add an explicit entry for 3.8. I don't have time to do it at the moment, but if someone else would like to take the lead on it please do so! :)

**Comment by rgommers** [comment]
Thanks @astrofrog. Indeed, the whole 1.21.x series has `pypy73` wheels, and the whole 1.22.x series `pypy38` wheels.

@mattip is there any preference for which numpy version to build against? Normally I'd suggest `1.22.0`, but maybe there are bug fixes in later versions that are needed for PyPy 3.8?

**Comment by mattip** [comment]
1.22.0 should be OK for pypy3.8, pypy3.9

**Comment by rgommers** [comment]
Closed by gh-57
