### ISSUE TITLE
Bump version & push to Pypi?

### ISSUE THREAD

**Issue by pv** [scipy/oldest-supported-numpy#6]
Would it make sense to push the current version of this to Pypi, to update the project home page urls etc? (And maybe add new maintainers on pypi to widen the bus factor.) Currently the links on pypi point to reproject.readthedocs.io

**Comment by rgommers** [comment]
+1 makes sense to me. https://pypi.org/project/oldest-supported-numpy/ looks outdated

**Comment by hamogu** [comment]
+1: I just noted the wrong project homepage URL as well.

**Comment by rgommers** [comment]
@astrofrog did you see this? It would also be useful to give `pv` and `rgommers` maintainer rights on PyPI.

**Comment by astrofrog** [comment]
@pv @rgommers - you are now both owners, and v0.3 is on PyPI.

**Comment by pv** [comment]
Thanks!

**Comment by rgommers** [comment]
Thanks @astrofrog
