### ISSUE TITLE
f2py broken on Windows until numpy 1.20.3 on Python <= 3.7

### ISSUE THREAD

**Issue by lpsinger** [scipy/oldest-supported-numpy#62]
I am finding that f2py was broken on Windows until numpy 1.20.3 due to numpy/numpy#17081, fixed by numpy/numpy#16468. Before I roll up my sleeves and start making the PR, would you consider a change to require numpy>=1.20.3 on Windows?

**Comment by rgommers** [comment]
That fix was backported to `1.19.0`: https://github.com/numpy/numpy/pull/16528, and https://github.com/numpy/numpy/pull/16468 is in `1.20.0`. So I think you are seeing another problem, can you double check @lpsinger?

**Comment by lpsinger** [comment]
Definitely failing in my cp37-win32 build. See https://github.com/nasa/radbelt/runs/8225863518?check_suite_focus=true.

**Comment by lpsinger** [comment]
This is probably because it is resolving to numpy==1.14.5 for Python 3.7 and numpy==1.17.3 for Python 3.8, which are both too old to have received the backport.

**Comment by rgommers** [comment]
Ah, that makes sense. This only impacts `f2py` users though; we cannot make that change because it will break package combinations or CI pipelines for other users. 

The solution for you here should be to add in your `pyproject.toml`:
```
    "numpy==1.19.5; python_version<='3.7'",  # see oldest-supported-nump issue 62
    "oldest-supported-numpy; python_version>='3.8'",
```

This comes up fairly regularly, I'd like to add a FAQ entry. We can really only change to a newer minor version of numpy if something is completely broken for everyone who could use the given version.

**Comment by lpsinger** [comment]
> This comes up fairly regularly, I'd like to add a FAQ entry. We can really only change to a newer minor version of numpy if something is completely broken for everyone who could use the given version.

Got it, thanks for the clarity on this. Do I take it that _you_ will write the FAQ entry (so no need for a PR from me)?

**Comment by lpsinger** [comment]
> The solution for you here should be to add in your `pyproject.toml`:
> 
> ```
>     "numpy==1.19.5; python_version<='3.7'",  # see oldest-supported-nump issue 62
>     "oldest-supported-numpy; python_version>='3.8'",
> ```

The environment markers must be more complicated than that because there are numerous other corner cases that are not handled by splitting on `python_version<='3.7'` or `python_version>='3.8'`: Darwin arm64, PyPy, etc. Constructing these environment markers correctly is in fact very tightly coupled to the dependencies of the _current version_ of oldest-supported-numpy. This will be quite difficult to maintain correctly independently of oldest-supported-numpy.

What about an extra, so that you can do this in your pyproject.toml?

```python
[build-system]
requires = [..., "oldest-supported-numpy[f2py]", ...]
`

**Comment by rgommers** [comment]
> The environment markers must be more complicated than that because there are numerous other corner cases that are not handled by splitting on `python_version<='3.7'` or `python_version>='3.8'`: Darwin arm64, PyPy, etc.

That is true, but only if you actually care about such corner cases. A few thoughts:
- Darwin arm64 for python <= 3.7 isn't really a thing, it's basically impossible to install. This one is safe to ignore,
- The AIX requirements are relevant indeed, if you expect folks to build from source on AIX (do you?),
- `aarch64` for Python 3.6/3.7 does matter indeed,
- `loongarch` isn't really a relevant thing yet,
- PyPy for py 3.6/3.7: yes that one matters, if your users use PyPy (does that work at all?),

> What about an extra, so that you can do this in your pyproject.toml?

Hmm. I have two questions there:
1. How would this even work? Normally an extra _adds_ something, but I don't quite see how that alone would work here when you want changes to the existing pins,
2. If it does work, how do we avoid accumulating more and more extras over time?

**Comment by rgommers** [comment]
> Do I take it that _you_ will write the FAQ entry (so no need for a PR from me)?

Yes, that is what I meant.

**Comment by lpsinger** [comment]
> > The environment markers must be more complicated than that because there are numerous other corner cases that are not handled by splitting on `python_version<='3.7'` or `python_version>='3.8'`: Darwin arm64, PyPy, etc.

Here is what I landed on:

```
            "numpy==1.19.0; python_version<='3.8' and platform_system=='Windows' and platform_python_implementation != 'PyPy'",
            "oldest-supported-numpy; python_version>'3.8' or platform_system!='Windows' or platform_python_implementation == 'PyPy'",
```

and excluding the following builds completely because they never had Numpy wheels:

`CIBW_SKIP='pp37-win_* pp37-macosx_*'`

> That is true, but only if you actually care about such corner cases. A few thoughts:
> 
> * Darwin arm64 for python <= 3.7 isn't really a thing, it's basically impossible to install. This one is safe to ignore,
> * The AIX requirements are relevant indeed, if you expect folks to build from source on AIX (do you?),
> * `aarch64` for Python 3.6/3.7 does matter indeed,
> * `loongarch` isn't really a relevant thing yet,
> * PyPy for py 3.6/3.7: yes that one matters, if your users use PyPy (does that work at all?),

I don't particularly care about any of those corner cases, but my goal is to use eventually use https://github.com/OpenAstronomy/github-actions-workflows which does not expose much of cibuildwheel's configuration and doesn't permit skipping builds.

> > What about an extra, so that you can do this in your pyproject.toml?
> 
> Hmm. I have two questions there:
> 
> 1. How would this even work? Normally an extra _adds_ something, but I don't quite see how that alone would work here when you want changes to the existing pins,
> 2. If it does work, how do we avoid accumulating more and more extras over time?

Good point. I can't think of a way to do this with extras.

**Comment by rgommers** [comment]
That looks nice and understandable.

Re https://github.com/OpenAstronomy/github-actions-workflows, skipping particular cibuildwheel builds seems pretty essential, by default cibuildwheel tries to do so much that I don't think I've ever seen a package with compiled code that didn't need a bunch of skips.

**Comment by astrofrog** [comment]
> which does not expose much of cibuildwheel's configuration and doesn't permit skipping builds.

It is possible to set any of the cibuildwheel options using pyproject.toml, and this works nicely with the OpenAstronomy workflows.

**Comment by rgommers** [comment]
Docs on this added in gh-63
