### ISSUE TITLE
Determine if specific constraints for Windows are necessary

### ISSUE THREAD

**Issue by cmarmo** [scipy/oldest-supported-numpy#65]
Dear maintainers,
I am opening this issue as a follow-up of the discussion started in https://github.com/scikit-learn/scikit-learn/issues/24669#issuecomment-1282981971.

I am not sure this is a real issue, but it probably needs some clarification outside the scikit-learn issue where it has been discussed.
I try to sum up my understanding.

There are no specific constraints on numpy versions for Windows on [setup.cfg](https://github.com/scipy/oldest-supported-numpy/blob/bbbdc562cac67ab474411dc06631aac84996f509/setup.cfg).

They were added in https://github.com/scipy/oldest-supported-numpy/pull/44, then reverted in https://github.com/scipy/oldest-supported-numpy/pull/47, after discussions in https://github.com/scipy/oldest-supported-numpy/issues/45.
Perhaps they are indeed not needed?

Feel free to close if this is not relevant.
Thanks for your attention.

**Comment by cmarmo** [comment]
Just linking here https://github.com/scikit-learn/scikit-learn/issues/24604
```
        ERROR: Cannot install numpy==1.21.6 and numpy==1.22.3 because these package versions have conflicting dependencies.

        The conflict is caused by:
            The user requested numpy==1.22.3
            The user requested numpy==1.21.6
```
Could this be related to scikit-learn using `old-supported-numpy` but not scipy so different versions of numpy are requested in this particular combination on Windows?

**Comment by rgommers** [comment]
This was discussed further and resolved on the linked scikit-learn issue. There's nothing to change here, so I'll close this issue. Thanks @cmarmo!
