### ISSUE TITLE
Error when using index URL and trusted host as command line arguments

### ISSUE THREAD

**Issue by david-cortes** [scipy/oldest-supported-numpy#68]
I am experiencing an error when using this package in a `pyproject.toml` file of a package that I try to install under the following conditions:
* I have a file `~/.pip/pip.conf` which defines a single index URL and trusted host (which is not PyPI).
* This host is inaccessible and/or doesn't have numpy packages.
* I am passing a different index URL and host (which correspond to PyPI's defaults) through command line arguments in the call to `pip`.

The call to `pip` then errors out with a message saying that the desired version of NumPy could not be found. Other build dependencies install just fine.

Not sure if the error is with this package or with `pip` or with something else though.

**Comment by rgommers** [comment]
That doesn't sound familiar at all, sorry @david-cortes. I am fairly sure it's on the `pip` side or on how your setup or the non-PyPI index is functioning. This package has no knowledge of that kind of thing at all, all it has is static metadata. 

Maybe your index server is indeed missing the required `numpy` version though? It must be the exact version that the error message is telling you.

**Comment by david-cortes** [comment]
> That doesn't sound familiar at all, sorry @david-cortes. I am fairly sure it's on the `pip` side or on how your setup or the non-PyPI index is functioning. This package has no knowledge of that kind of thing at all, all it has is static metadata.
> 
> Maybe your index server is indeed missing the required `numpy` version though? It must be the exact version that the error message is telling you.

It is - however, I am passing arguments `--index-url` and `--trusted-host` in the call to `pip`, which means it should not be looking at the url/host from my config, just at the one that I am passing in the command line arguments. But in this case, it seems it's still looking at the index/host on my config file.

**Comment by rgommers** [comment]
I'll close this as not actionable - this must be a `pip` bug or "feature". In case there is a change to be made, please feel free to propose it of course, and we can reopen.
