### ISSUE TITLE
Drop support for EOL pythons?

### ISSUE THREAD

**Issue by h-vetinari** [scipy/oldest-supported-numpy#72]
I think we should drop the markers for 3.5 and probably 3.6, and just raise `python_requires` appropriately. Those on old python versions will still get functioning `oldest-supported-numpy` packages, and almost by definition, those old language versions will not receive any new architecture support. However, they still have a maintenance cost, as seen in cases like #71, so I think we should drop them.

Python 3.7 is also [EOL](https://peps.python.org/pep-0537/) this month, but it's a borderline case.

**Comment by h-vetinari** [comment]
Python 3.5 has also already been dropped from `test_dependencies.py`...

**Comment by rgommers** [comment]
That sounds okay to me indeed. We should keep 3.7 for a little while longer.
