### ISSUE TITLE
Run more installation tests in QEMU?

### ISSUE THREAD

**Issue by h-vetinari** [scipy/oldest-supported-numpy#73]
Currently we only run the installation tests on x64, but with something like [`run-on-arch`](https://github.com/marketplace/actions/run-on-architecture) we could relatively easily (within the GHA framework) also run on most other architectures (only loongarch is not supported yet).

**Comment by rgommers** [comment]
I'm okay with adding them if someone wants to do the work, but given that we're going to phase out this package I can't say I see much value in spending time on it now.

**Comment by rgommers** [comment]
I'll close this, since we're phasing out this package (and that's going to happen quite soon I think, given 2.0 changes) I'd say we just shouldn't do this.
