### ISSUE TITLE
Add Python 3.9 entry

### ISSUE THREAD

**Issue by astrofrog** [scipy/oldest-supported-numpy#8]
We should check whether we already know which Numpy version will be the first to support Python 3.9 and add an entry - ideally before 3.9 final is released, to avoid any breakage.

**Comment by rgommers** [comment]
Good question. I don't know if we have a release yet that works with 3.9. 3.9.0rc2 should be out, so things must be stable enough. @charris or @mattip do you know what the lowest NumPy version is that supports Python 3.9?

**Comment by charris** [comment]
I'm planning to release 3.9 wheels for 1.19 once we are able to build them on all the supported platforms. That means that we need to wait until 3.9 is available on azure and ideally in the docker images also. @mattip is tracking the issue. I haven't tried building 1.18 with 3.9, there were 3.9 fixes that went into 1.19 so it may not be possible to build earlier versions out of the box.

**Comment by rgommers** [comment]
Thanks Chuck! I'm not sure if you will be able to add new wheels for 1.19.2, or need to do a 1.19.3. So I guess we'll just wait with a next release of this package.

**Comment by charris** [comment]
There will definitely be a 1.19.3. The two outstanding issues are fixing OpenBLAS libraries for Windows 2004 and adding 3.9 support.

**Comment by astrofrog** [comment]
Done in #9 and v0.6 is now released
